### ISSUE TITLE
Failing to subscribe to topics

### ISSUE THREAD

**Issue by psp515** [Deve-Lite/DashboardX-App#58]
Problem:
When 2 or more brokers has same server url program is unable to create two instances of connection

Fix Proposoal:
1 - When adding new brokers check if user has broker with similar server if yes return error. @dredziasty can this be implemented?
2 - Disconnect brokers with same server url and connect only new one. 
3 - Create Service just to store brokers connections. (What if 2 brokers has different oprions)

**Comment by dredziasty** [comment]
Yup, if server already exists for a specific user i'll throw a HTTP 409,for both endpoints POST and PATCH
