### ISSUE TITLE
On Broker Delete

### ISSUE THREAD

**Issue by psp515** [Deve-Lite/DashboardX-App#65]
After deleting broker devices are not removed and this currently causes application error. Fixed.

TODO: After deleting broker Devices without broker should also be displayed in devices list

**Comment by psp515** [comment]
@dredziasty Can we currently after delete broker delete all connected resources ? It will make app easier and we will add it to feature for future. Thanks to that we will be able to deploy app faster.

**Comment by dredziasty** [comment]
What kind of issue does it cause? You list devices per broker so unassigned ones should not be pulled by the App

**Comment by psp515** [comment]
There is also screen to list all devices.

**Comment by dredziasty** [comment]
Is it so much effort to filter out devices with `brokerId == null`?

**Comment by psp515** [comment]
I guess it will not be, ok so nvm i will  compare brokerId == null. (when first I was writin i was thinking about database space but it doestn matter actually)

**Comment by dredziasty** [comment]
Got it, it's not big deal to get rid of data on production's db if we'll get overloaded with unnecessary data
